#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
	 "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" \
  1>"/dev/null" || \
source \
  "${_crash_bash}"

_activity-launch_requirements() {
  _check_cmd \
    "activity-launch" \
    "android-activity-utils"
  _check_cmd \
    "activity-focused" \
    "android-activity-utils"
}

_input_requirements() {
  _check_cmd \
    "sudo" \
    "sudo"
  # _check_cmd \
  #   "key2keyevent" \
  #   "android-input-utils"
}

_requirements() {
  _check_cmd \
    "awk" \
    "gawk"
  _check_cmd \
    "grep"
}

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  get_mode=""
  hover_only=""
  release_alt=""
  target_window=""
  color=""
  quiet=""
}

_alt_tab_cmd() {
  sudo \
    input \
      keyevent \
        --longpress \
        "${_alt}"
  sudo \
    input \
      keycombination \
        "${_alt}" \
        "${_tab}"
  if (( 1 < "${_target_window}" )); then
    for _window \
      in $(seq \
             "2" \
             "${_target_window}"); do
      sudo \
        input \
          keycombination \
            "${_alt}" \
            "${_tab}"
    done
  fi
}


_input_run() {
  local \
    _hover_only="${1}" \
    _release_alt="${2}" \
    _target_window="${3}" \
    _alt \
    _tab
  # _alt="$(
  #   key2keyevent \
  #     "alt_left")"
  _alt=57
  # _tab="$(
  #   key2keyevent \
  #     "tab")"
  _tab=61
  if [[ "${_release_alt}" == "n" ]]; then
    _alt_tab_cmd \
      "${_target_window}"
  fi
  if [[ "${_hover_only}" == "n" || \
        "${_release_alt}" == "y" ]]; then
    sudo \
      input \
        keyevent \
          --longpress \
          "${_alt}"
  fi
}

_activity-launch_run() {
  local \
    _target_window="${1}" \
    _activity_current
  _activity_current="$(
    activity-focused)"
  windows-list
}

_alt_tab() {
  local \
    _mode="${1}" \
    _hover_only="${2}" \
    _release_alt="${3}" \
    _target_window="${4}" \
    _cmd=() \
    _activities \
    _args=()
  "_${_mode}_requirements"
  if [[ "${_mode}" == "input" ]]; then
    _args+=(
      "${_hover_only}"
      "${_release_alt}"
      "${_target_window}"
    )
  elif [[ "${_mode}" == "activity-launch" ]]; then
    _args+=(
      "${_target_window}"
    )
  fi
  "_${_mode}_run" \
    "${_args[@]}"
}

_auto_detect_mode() {
  local \
    _os \
    _msg=()
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _input_requirements
    echo \
      "input"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg=(
      "Not implemented."
      "Something with 'xdotool'"
      "needs to be written."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "get" \
    "mode" \
    "$(_auto_detect_mode)"
  _set_override \
    "hover" \
    "only" \
    "n"
  _set_override \
    "release" \
    "alt" \
    "n"
  _set_override \
    "target" \
    "window" \
    1
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "             Got activity at date:   ${get_date}"
  _msg_info "                    Switch method:   ${get_mode}"
  _msg_info "                       Hover only:   ${hover_only}"
  _msg_info "                      Release alt:   ${release_alt}"
  _msg_info " Target previously focused window:   ${target_window}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Switches to a previously focused application.

Usage:

  ${app_name}
    [options]

  options:

     -N <windows>

       To which previously focused window
       from the current one to go back.
       Default: ${target_window}

     -p

       Hover only, as in do the Alt+Tab
       switch but do not release the Alt
       key.
       You may want to do this to initiate
       an window switch action for an
       interactive switch.

     -r

       Release Alt key. You may want to
       use this option after you've selected
       the window you want to select after
       running the program with the '-p' option.

     -m <method>

       Method to perform the switch.
       All require administrative permissions.
       It can be:
       - input:
           It performs the action using
           the 'input' command,
       - activity-launch:
           It retrieves open windows list
           and runs the corresponding past
           activity. It avoids one to
           concretely press alt+tab but it
           may not work depending on the
           activity.
       Default: ${get_mode}
                              
     -h

       This message.

     -c

       Enable color output.

     -v

       Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:N:dcvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_get_mode="${OPTARG}" ;;
    N)
      override_target_window="${OPTARG}" ;;
    p)
      override_hover_only="${OPTARG}" ;;
    r)
      override_release_alt="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "${get_mode}"
  "${hover_only}"
  "${release_alt}"
  "${target_window}"
)
_show_config
_alt_tab \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
