#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" \
  1>"/dev/null" || \
source \
  "${_crash_bash}"

_root_requirements() {
  _check_cmd \
    "awk" \
    "gawk"
  _check_cmd \
    "sdk-version" \
    "android-utils"
  _check_cmd \
    "sed"
  _check_cmd \
    "su"
}

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  get_mode=""
  output_format=""
  color=""
  quiet=""
}

_root_get() {
  local \
    _dumpsys \
    _cmd \
    _msg=() \
    _sdk
  _sdk="$(
    sdk-version)"
  _msg=(
    "Detected SDK version '${_sdk}'."
  )
  _msg_info \
    "${_msg[*]}"
  if (( 32 < "${_sdk}" )); then
    _cmd=(
      "/system/bin/dumpsys"
        "window"
        "windows"
    )
    # _cmd=(
    #   "/system/bin/dumpsys"
    #     "activity"
    #     "activities"
    # )
  elif (( "${_sdk}" < 28 )); then
    _cmd=(
      "/system/bin/dumpsys"
        "window"
        "windows"
    )
  else
    _cmd=(
      "/system/bin/dumpsys"
        "window"
        "windows"
    )
  fi
  _msg=(
    "Running '${_cmd[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _dumpsys="$(
    su \
      -c \
      "${_cmd[*]}" || \
      true)"
  if [[ "${_dumpsys}" == "" ]]; then
    _msg=(
      "Error running '${_cmd[*]}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  "_dumpsys_${_output_format}_encode" \
    "${_dumpsys}"
}

_dumpsys_plain_encode() {
  local \
    _dumpsys="${1}"
  echo \
    "${_dumpsys}"
}

_window_json_get() {
  local \
    _msg=() \
    _jq_opts=() \
    _attrs \
    _attrs_encode_opts=() \
    _flags_jq_arg \
    _flags_json \
    _flags_encode_opts=() \
    _msurface \
    _msurface_ecode_opts=() \
    _private_flags_jq_arg \
    _private_flags_json \
    _private_flags_encode_opts=() \
    _session \
    _session_encode_opts=() \
    _state_animator \
    _state_animator_encode_opts=() \
    _token \
    _token_encode_opts=() \
    _window_encode_opts=() \
    _msg=()
  _msurface=""
  _msg=(
    "Encoding window object JSON."
  )
  _msg_info \
    "${_msg[*]}"
  _jq_opts+=(
    -n
  )
  _msg=(
    "Getting session JSON."
  )
  _msg_info \
    "${_msg[*]}"
  _session_encode_opts+=(
    --arg
      "id"
        "${_session_id}"
    --arg
      "unknown-session-id"
        "${_user_word}"
    --arg
      "app-uid":
        "${_uid}"
    --arg
      "app-user-name":
        "${_app_user_name}"
    --arg
      "mClient":
        "${_client}"
    '$ARGS.named'
  )
  _msg=(
    "Running jq with options"
    "'${_jq_opts[*]}"
    "${_session_encode_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _session="$(
    jq \
      "${_jq_opts[@]}" \
      "${_session_encode_opts[@]}")"
  _msg=(
    "Getting flags JSON."
  )
  _msg_info \
    "${_msg[*]}"
  _flags_jq_arg="[$(
    IFS=","; \
    echo \
      "${_flags[*]}")]"
  _flags_encode_opts+=(
    --argjson
      "flags"
        "${_flags_jq_arg}"
    '$ARGS.named.flags'
  )
  _msg=(
    "Running jq with options"
    "'${_jq_opts[*]}"
    "${_flags_encode_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _flags_json="$(
    jq \
      "${_jq_opts[@]}" \
      "${_flags_encode_opts[@]}")"
  _msg=(
    "Flags JSON: ${_flags_json}"
  )
  _msg_info \
    "${_msg[*]}"
  _msg=(
    "Getting private flags JSON."
  )
  _msg_info \
    "${_msg[*]}"
  _private_flags_jq_arg="[$(
    IFS=","; \
    echo \
      "${_private_flags[*]}")]"
  _private_flags_encode_opts+=(
    --argjson
      "pflags"
        "${_private_flags_jq_arg}"
    '$ARGS.named.pflags'
  )
  _msg=(
    "Running jq with options"
    "'${_jq_opts[*]}"
    "${_private_flags_encode_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _private_flags_json="$(
    jq \
      "${_jq_opts[@]}" \
      "${_private_flags_encode_opts[@]}")"
  _msg=(
    "Private flags JSON: ${_private_flags_json}"
  )
  _msg_info \
    "${_msg[*]}"
  _attrs_encode_opts+=(
    --arg
      "position-layout"
        "${_position_layout}"
    --arg
      "position"
        "${_position}"
    --arg
      "layout"
        "${_layout}"
    --argjson
      "fl"
        "${_flags_json}"
    --argjson
      "pfl"
        "${_private_flags_json}"
    --arg
      "bhv"
        "${_behavior}"
    --arg
      "fitSides"
        "${_fit_sides}"
    '$ARGS.named'
  )
  _attrs="$(
    jq \
      "${_jq_opts[@]}" \
      "${_attrs_encode_opts[@]}")"
  _token_encode_opts+=(
    --arg
      "id"
        "${_window_token_id}"
    --arg
      "type"
        "${_token_type}"
    --arg
      "window-grouping-token"
        "${_window_grouping_token}"
    '$ARGS.named'
  )
  _msg=(
    "Running jq with options"
    "'${_jq_opts[*]}"
    "${_token_encode_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _token="$(
    jq \
      "${_jq_opts[@]}" \
      "${_token_encode_opts[@]}")"
  _msg=(
    "Window token JSON: ${_token}"
  )
  _msg_info \
    "${_msg[*]}"
  _frames_encode_opts+=(
    --arg
      "display"
        "${_frames_display}"
    --arg
      "frame"
        "${_frames_frame}"
    --arg
      "last"
        "${_frames_last}"
    --arg
      "surface"
        "${_frames_surface}"
  )
  if [[ "${_frames_insets_change}" != "" ]]; then
    _frames_encode_opts+=(
      --arg
        "insetsChange"
          "${_frames_insets_change}"
    )
  fi
  if [[ "${_frames_insets_changed}" != "" ]]; then
    _frames_encode_opts+=(
      --arg
        "insetsChanged"
          "${_frames_insets_changed}"
    )
  fi
  _frames_encode_opts+=(
    '$ARGS.named'
  )
  _msg=(
    "Running jq with options"
    "'${_jq_opts[*]}"
    "${_frames_encode_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _frames="$(
    jq \
      "${_jq_opts[@]}" \
      "${_frames_encode_opts[@]}")"
  _msg=(
    "Window frames JSON: ${_frames}"
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${_surface_id}" != "" ]]; then
    _msurface_encode_opts+=(
      --arg
        "name"
          "${_surface_name}"
      --arg
        "id"
          "${_surface_id}"
      '$ARGS.named'
    )
    _msg=(
      "Running jq with options"
      "'${_jq_opts[*]}"
      "${_msurface_encode_opts[*]}'."
    )
    _msg_info \
      "${_msg[*]}"
    _msurface="$(
      jq \
        "${_jq_opts[@]}" \
        "${_msurface_encode_opts[@]}")"
    _msg=(
      "Window frames JSON: ${_msurface}"
    )
    _msg_info \
      "${_msg[*]}"
  fi
  _state_animator_encode_opts+=(
    --arg
      "id"
        "${_state_animator_id}"
    --arg
      "owner"
        "${_state_animator_owner}"
  )
  if [[ "${_msurface}" != "" ]]; then
    _state_animator_encode_opts+=(
      --argjson
        "mSurface"
          "${_msurface}"
    )
  fi
  _state_animator_encode_opts+=(
    '$ARGS.named'
  )
  _msg=(
    "Running jq with options"
    "'${_jq_opts[*]}"
    "${_state_animator_encode_opts[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _state_animator="$(
    jq \
      "${_jq_opts[@]}" \
      "${_state_animator_encode_opts[@]}")"
  _msg=(
    "Window State Animator JSON: ${_state_animator}"
  )
  _msg_info \
    "${_msg[*]}"
  _window_encode_opts+=(
      --arg
        "id"
          "${_id}"
      --arg
        "user-id"
          "${_user_id}"
      --arg
        "activity"
          "${_activity}"
      --arg
        "mDisplayId"
          "${_display_id}"
      --arg
        "rootId"
          "${_display_id}"
      --argjson
        "mAttrs"
          "${_attrs}"
      --argjson
        "mSession"
          "${_session}"
      --argjson
        "mToken"
          "${_token}"
      --arg
        "mOwnerUid"
          "${_owner_uid}"
      --arg
        "showForAllUsers"
          "true"
      --arg
        "package"
          "${_package}"
      --arg
        "appop"
          "${_app_op}"
      --arg
        "w"
          "${_requested_width}"
      --arg
        "h"
          "${_requested_height}"
      --arg
        "mLayoutSeq"
          "${_layout_sequence_number}"
      --arg
        "mBaseLayer"
          "${_base_layer}"
      --arg
        "mSubLayer"
          "${_sub_layer}"
      --arg
        "mViewVisibility"
          "${_view_visibility}"
      --arg
        "mHaveFrame"
          "${_have_frame}"
      --arg
        "mObscured"
          "${_view_obscured}"
      --arg
        "mGivenContentInsets"
          "${_given_content_insets}"
      --arg
        "mGivenVisibleInsets"
          "${_given_visible_insets}"
      --arg
        "mFullConfiguration"
          "${_full_configuration_string}"
      --arg
        "mLastReportedConfiguration"
          "${_last_reported_configuration_string}"
      --argjson
        "Frames"
          "${_frames}"
      --argjson
        "WindowStateAnimator"
          "${_state_animator}"
      '$ARGS.named'
  )
  _window="$(
    jq \
      "${_jq_opts[@]}" \
      "${_window_encode_opts[@]}")"
  _msg=(
    "Detected window ${_index},"
    "extracted:"
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${quiet}" == "n" ]]; then
    echo \
      "${_window}"
  fi
  _window=""
}

_values_clean() {
  _app_op=""
  _app_op_word=""
  _app_user=""
  _app_user_id=""
  _app_user_name=""
  _base_layer=""
  _base_layer_word=""
  _behavior=""
  _behavior_word=""
  _client_word=""
  _client=""
  _display_id=""
  _display_id_word=""
  _fit_sides=""
  _fit_sides_word=""
  _fl=""
  _fl_word=""
  _flags=()
  _full_configuration_string=""
  _given_content_insets=""
  _given_content_insets_word=""
  _given_visible_insets=""
  _given_visible_insets_word=""
  _frames_display=""
  _frames_frame=""
  _frames_insets_change=""
  _frames_insets_changed=""
  _frames_last=""
  _frames_last_word=""
  _frames_parent=""
  _frames_surface=""
  _frames_surface_word=""
  _have_frame=""
  _have_frame_word=""
  _has_surface=""
  _has_surface_word=""
  _is_ready_for_display=""
  _is_ready_for_display_word=""
  _last_reported_configuration_string=""
  _layout=""
  _layout_sequence_number=""
  _layout_sequence_number_word=""
  _owner_uid=""
  _owner_uid_word=""
  _package=""
  _package_word=""
  _pfl=""
  _pfl_word=""
  _position=""
  _position_layout=""
  _position_layout_word=""
  _private_flags=()
  _requested_height=""
  _requested_height_word=""
  _requested_width=""
  _requested_width_word=""
  _root_task_id=""
  _root_task_id_word=""
  _session_id=""
  _session_id_word=""
  _session_unknown_id=""
  _show_for_all_users=""
  _show_for_all_users_word=""
  _state_animator_id=""
  _state_animator_id_word=""
  _state_animator_owner=""
  _state_animator_owner_word=""
  _sub_layer=""
  _sub_layer_word=""
  _surface_name=""
  _surface_name_word=""
  _surface_id=""
  _token_type=""
  _uid=""
  _user_unknown_id=""
  _user_word=""
  _view_obscured=""
  _view_obscured_word=""
  _view_visibility=""
  _view_visibility_word=""
  _window_grouping_token=""
  _window_removal_allowed=""
  _window_removal_allowed_word=""
  _window_token_id=""
  _window_token_id_word=""
  _window_token_type=""
}

_dumpsys_json_encode() {
  local \
    _dumpsys="${1}" \
    _dumpsys_window_windows=() \
    _id \
    _activity \
    _activity_word \
    _app_user \
    _app_user_id \
    _app_user_name \
    _app_op \
    _app_op_word \
    _base_layer \
    _base_layer_word \
    _client \
    _client_word \
    _fit_sides \
    _fit_sides_word \
    _fl \
    _fl_word \
    _flag \
    _flags=() \
    _frames_display \
    _frames_frame \
    _frames_insets_change \
    _frames_insets_changed \
    _frames_last \
    _frames_last_word \
    _frames_parent \
    _frames_surface \
    _frames_surface_word \
    _full_configuration_string \
    _given_content_insets \
    _given_content_insets_word \
    _given_visible_insets \
    _given_visible_insets_word \
    _have_frame \
    _have_frame_word \
    _index \
    _index_display \
    _last_reported_configuration_string \
    _layout \
    _layout_sequence_number_word \
    _layout_sequence_number \
    _line=() \
    _line_string \
    _owner_uid_word \
    _owner_uid \
    _package \
    _package_word \
    _pfl \
    _pfl_word \
    _position_layout_word \
    _position_layout \
    _position \
    _private_flags=() \
    _requested_width \
    _requested_width_word \
    _requested_height \
    _requested_height_word \
    _root_task_id \
    _root_task_id_word \
    _session_id \
    _session_id_word \
    _show_for_all_users \
    _show_for_all_users_word \
    _state_animator_id \
    _state_animator_id_word \
    _state_animator_owner \
    _state_animator_owner_word \
    _surface_id \
    _surface_name \
    _surface_name_word \
    _sub_layer \
    _sub_layer_word \
    _token_type \
    _uid \
    _user_id \
    _user_unknown_id \
    _user_word \
    _view_obscured \
    _view_obscured_word \
    _view_visibility \
    _view_visibility_word \
    _msg=() \
    _window \
    _window_grouping_token \
    _window_token_id \
    _window_token_id_word \
    _window_token_type
  _msg=(
    "Encoding dumpsys output"
    "in JSON format."
  )
  _msg_info \
    "${_msg[*]}"
  mapfile \
    -d \
      $'\n' \
    _dumpsys_window_windows < \
    <(echo \
        "${_dumpsys}")
  _msg=(
    "Dumpsys output is '${#_dumpsys_window_windows[@]}'"
    "lines long."
  )
  _msg_info \
    "${_msg[*]}"
  _index=-1
  _window=""
  for _line_string in "${_dumpsys_window_windows[@]}"; do
    _line=(
      ${_line_string}
    )
    if [[ "${_line_string}" == "  Window #"* ]]; then
      _index_display="$((
        _index + 1))"
      _msg=(
        "Parsing window '${_index_display}' line."
      )
      _msg_info \
        "${_msg[*]}"
      if (( -1 < "${_index}" )); then
        _window_json_get
      fi
      _index="$((
        _index + 1 ))"
      _id="$(
        echo \
          "${_line[2]}" |
            sed \
              's/Window{//g')"
      _user_id="${_line[3]}"
      _activity_word="${_line[4]}"
      _activity="${_activity_word%*\}:}"
      _values_clean
    elif [[ "${_line_string}" == "    mDisplayId="*" rootTaskId="*" mSession="*" mClient="* ]]; then
      _msg=(
        "Parsing display/session/client line."
      )
      _msg_info \
        "${_msg[*]}"
      _display_id_word="${_line[0]}"
      _display_id="${_display_id_word##mDisplayId=}"
      _root_task_id_word="${_line[1]}"
      _root_task_id="${_root_task_id_word##rootTaskId=}"
      _session_id_word="${_line[2]}"
      _session_id="${_session_id_word##mSession=Session\{}"
      _user_word="${_line[3]}"
      _session_unknown_id="${_user_word%%:*}"
      _user_unknown_id="${_user_word%%:*}"
      _app_user="${_user_word##*:}"
      _app_user_id="${_app_user##${_user_id}}"
      _app_user_id="${_app_user_id%\}}"
      _uid="${_app_user_id#a}"
      if [[ "${_app_user_id}" == "a"* ]]; then
        _app_user_name="${_user_id}_a${_uid#10}"
      else
        _app_user_name="$(
          id \
            -un \
            "${_uid}")"
      fi
      _client_word="${_line[4]}"
      _client="${_client_word#mClient=}"
    elif [[ "${_line_string}" == "    mOwnerUid="*" showForAllUsers="*" package="*" appop="* ]]; then
      _msg=(
        "Parsing owner-uid/visibility/package line."
      )
      _msg_info \
        "${_msg[*]}"
      _owner_uid_word="${_line[0]}"
      _owner_uid="${_owner_uid_word#mOwnerUid=}"
      _show_for_all_users_word="${_line[1]}"
      _show_for_all_users="${_show_for_all_users_word#showForAllUsers=}"
      _package_word="${_line[2]}"
      _package="${_package_word#package=}"
      _app_op_word="${_line[3]}"
      _app_op="${_app_op_word#appop=}"
    elif [[ "${_line_string}" == "    mAttrs={"* ]]; then
    # elif [[ "${_line_string}" == "    mAttrs={"*" sim="*"{"*"state="*" adjust="*" ty="*" fmt="*" wanim="*" sysuil="* ]]; then
      _msg=(
        "Parsing first attributes line."
      )
      _msg_info \
        "${_msg[*]}"
      _position_layout_word="${_line[0]}"
      _position_layout="${_position_layout_word#mAttrs=\{}"
      _position="${_position_layout%(*}"
      _layout="${_position_layout#*)}"
    elif [[ "${_line_string}" == "      fl="* ]]; then
      _fl_word="${_line[0]}"
      _fl="${_fl_word#fl=}"
      _flags+=(
        "\"${_fl}\""
      )
      for _flag in "${_line[@]:1}"; do
        _flags+=(
          "\"${_flag}\""
        )
      done
    elif [[ "${_line_string}" == "      pfl="* ]]; then
      _pfl_word="${_line[0]}"
      _pfl="${_pfl_word#pfl=}"
      _private_flags+=(
        "\"${_pfl}\""
      )
      for _flag in "${_line[@]:1}"; do
        _private_flags+=(
          "\"${_flag}\""
        )
      done
    elif [[ "${_line_string}" == "      bhv="* ]]; then
      _behavior_word="${_line[0]}"
      _behavior="${_behavior_word#bhv=}"
      _behavior="${_behavior#%\}}"
    elif [[ "${_line_string}" == "      fitSides="* ]]; then
      _fit_sides_word="${_line[0]}"
      _fit_sides="${_fit_sides_word#fitSides=}"
      _fit_sides="${_fit_sides%\}}"
    elif [[ "${_line_string}" == "    Requested"*" w="*" h="*" mLayoutSeq="* ]]; then
      _requested_width_word="${_line[1]}"
      _requested_width="${_requested_width_word#w=}"
      _requested_height_word="${_line[2]}"
      _requested_height="${_requested_height_word#h=}"
      _layout_sequence_number_word="${_line[3]}"
      _layout_sequence_number="${_layout_sequence_number_word#mLayoutSeq=}"
    elif [[ "${_line_string}" == "    mBaseLayer"*" mSubLayer="*" mToken="* ]]; then
      _base_layer_word="${_line[0]}"
      _base_layer="${_base_layer_word#mBaseLayer=}"
      _sub_layer_word="${_line[1]}"
      _sub_layer="${_sub_layer_word#mSubLayer=}"
      _window_token_id_word="${_line[2]}"
      _window_token_id="${_window_token_id_word#mToken=WindowToken\{}"
      if [[ "${_window_token_id_word}" == "${_window_token_id}" ]]; then
        _window_token_type="${_window_token_id_word#mToken=}"
        _window_token_type="${_window_token_type%\{}"
        _msg=(
          "Unknown token type '${_window_token_type}'"
          "at line '${_line_string}' in output"
          "of 'dumpsys window windows'."
        )
        _msg_error \
          "${_msg[*]}" \
          1
      fi
      for _word in "${_line[@]:3}"; do
        if [[ "${_word}" == "type="* ]]; then
          _token_type="${_word#type=}"
        elif [[ "${_word}" == "android.os.Binder@"* ]]; then
          _window_grouping_token="${_word%\}}"
        elif [[ "${_word}" == "android.os.BinderProxy@"* ]]; then
          _window_grouping_token="${_word%\}}"
        elif [[ "${_word}" == "android.view.ViewRootImpl\$W@"* ]]; then
          _window_grouping_token="${_word%\}}"
        else
          _msg=(
            "Unknown property '${_word}'"
            "for 'WindowToken' object."
          )
          _msg_error \
            "${_msg[*]}" \
            1
        fi
      done
    elif [[ "${_line_string}" == "    mViewVisibility="*" mHaveFrame="*" mObscured="* ]]; then
      _view_visibility_word="${_line[0]}"
      _view_visibility="${_view_visibility_word#mViewVisibility=}"
      _have_frame_word="${_line[1]}"
      _have_frame="${_have_frame_word#mHaveFrame=}"
      _view_obscured_word="${_line[2]}"
      _view_obscured="${_view_obscured_word#mObscured=}"
    elif [[ "${_line_string}" == "    mGivenContentInsets="*" mGivenVisibleInsets="* ]]; then
      _given_content_insets_word="${_line[0]}"
      _given_content_insets="${_given_content_insets_word#mGivenContentInsets=}"
      _given_visible_insets_word="${_line[1]}"
      _given_visible_insets="${_given_visible_insets_word#mGivenVisibleInsets=}"
    elif [[ "${_line_string}" == "    mFullConfiguration="* ]]; then
      _full_configuration_string="${_line_string#    mFullConfiguration=\{}"
      _full_configuration_string="${_full_configuration_string%\}}"
      _full_configuration_string_parse \
        "${_full_configuration_string}"
    elif [[ "${_line_string}" == "    mLastReportedConfiguration="* ]]; then
      _last_reported_configuration_string="${_line_string#    mLastReportedConfiguration=\{}"
      _last_reported_configuration_string="${_last_reported_configuration_string%\}}"
      _full_configuration_string_parse \
        "${_last_reported_configuration_string}"
    elif [[ "${_line_string}" == "    mHasSurface="*" isReadyForDisplay()="*" mWindowRemovalAllowed="* ]]; then
      _has_surface_word="${_line[0]}"
      _has_surface="${_has_surface_word#mHasSurface=}"
      _is_ready_for_display_word="${_line[1]}"
      _is_ready_for_display="${_is_ready_for_display_word#mHasSurface=}"
      _window_removal_allowed_word="${_line[2]}"
      _window_removal_allowed="${_window_removal_allowed_word#mWindowRemovalAllowed=}"
    elif [[ "${_line_string}" == "    Frames: "* ]]; then
      for _word in "${_line[@]}"; do
        if [[ "${_word}" == "parent="* ]]; then
          _frames_parent="${_word#parent=}"
        elif [[ "${_word}" == "display="* ]]; then
          _frames_display="${_word#display=}"
        elif [[ "${_word}" == "frame="* ]]; then
          _frames_frame="${_word#frame=}"
        elif [[ "${_word}" == "last="* ]]; then
          _frames_last="${_word#last=}"
        elif [[ "${_word}" == "insetsChange="* ]]; then
          _frames_insets_change="${_word#insetsChange=}"
        elif [[ "${_word}" == "insetsChanged="* ]]; then
          _frames_insets_changed="${_word#insetsChanged=}"
        fi
      done
insetsChanged=false
    elif [[ "${_line_string}" == "      surface="* ]]; then
      _frames_surface_word="${_line[0]}"
      _frames_surface="${_frames_surface_word#surface=}"
    elif [[ "${_line_string}" == "    WindowStateAnimator={"* ]]; then
      _state_animator_id_word="${_line[0]}"
      _state_animator_id="${_state_animator_id_word#WindowStateAnimator\{}"
      _state_animator_owner_word="${_line[1]}"
      _state_animator_owner="${_state_animator_owner_word%\}:}"
    elif [[ "${_line_string}" == "      mSurface=Surface("* ]]; then
      _surface_name_word="${_line[0]}"
      _surface_name="${_surface_name_word#mSurface=Surface\(name=}"
      _surface_name="${_surface_name%\)*}"
      _surface_id="${_surface_name_word##*\/}"
    else
      true
      # echo \
      #   "${_line}"
    fi
  done
  # echo \
  #   "${_window}"
}

_full_configuration_string_parse() {
  local \
    _full_configuration_string="${1}" \
    _line=() \
    _win_config_flag \
    _word
  _line=(
    ${_full_configuration_string}
  )
  _win_config_flag="false"
  # at the end.
  # for _word in "${_line[@]}"; do
  #   if [[ ]]; then
  #   fi
  # done
  # true
  # TODO:
  #   this is an example string of the type it
  #   gets given in input to this function
  #   I dont need fully parsed right now so it can stay
  #   a string as far as I'm concerned.
  #   Feel free to do it yourself.
  #   mFullConfiguration={
  #     2.0
  #     222mcc8mnc
  #     [en_US,it_IT]
  #     ldltr sw480dp
  #     w1067dp
  #     h480dp
  #     72dpi
  #     lrg
  #     long
  #     land
  #     night
  #     finger
  #     -keyb/v/h
  #     -nav/h
  #     winConfig={
  #       mBounds=Rect(0, 0 - 480, 216)
  #       mAppBounds=Rect(0, 0 - 480, 216)
  #       mMaxBounds=Rect(0, 0 - 480, 216)
  #       mDisplayRotation=ROTATION_90
  #       mWindowingMode=fullscreen
  #       mDisplayWindowingMode=fullscreen
  #       mActivityType=undefined
  #       mAlwaysOnTop=undefined
  #       mRotation=ROTATION_90}
  #       as.16
  #       s.6006
  #       fontWeightAdjustment=0}
}

_windows_info() {
  local \
    _mode="${1}" \
    _output_format="${2}" \
    _output_info \
    _cmd=() \
    _activities
  "_${_mode}_get"
}

_auto_detect_mode() {
  local \
    _os \
    _msg=()
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _root_requirements
    echo \
      "root"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg=(
      "Not implemented."
      "Something with 'xdotool'"
      "needs to be written."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "get" \
    "mode" \
    "$(_auto_detect_mode)"
  _set_override \
    "get" \
    "mode" \
    "$(_auto_detect_mode)"
  _set_override \
    "output" \
    "format" \
    "json"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "     Got activity at date:   ${get_date}"
  _msg_info "                 Get mode:   ${get_mode}"
  _msg_info "            Output format:   ${output_format}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Returns informations about currently opened windows.

Usage:

  ${app_name}
    [options]

  options:

     -o                   Output format.
                          It can be 'json' or 'plain'.
                          Default: ${output_format}

     -h                   This message.
     -c                   Enable color output.
     -v                   Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:o:cvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_get_mode="${OPTARG}" ;;
    o)
      override_output_format="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "${get_mode}"
  "${output_format}"
)
_show_config
_windows_info \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
