#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" \
  1>"/dev/null" || \
source \
  "${_crash_bash}"

_description_requirements() {
  _check_cmd \
    "activities-info" \
    "android-activity-utils"
}

_label_requirements() {
  _check_cmd \
    "app-name" \
    "android-app-utils"
}

_requirements() {
  _check_cmd \
    "grep"
  _check_cmd \
    "sort" \
    "coreutils"
}

_root_requirements() {
  _check_cmd \
    "su" \
    "sudo"
}

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  get_mode=""
  output_template=""
  title_format=""
  output_format=""
  color=""
  quiet=""
}

_root_get() {
  local \
    _output_template="${1}" \
    _output_format="${2}" \
    _title_format="${3}" \
    _activities_info_opts=() \
    _infos_flag \
    _msg=() \
    _template=() \
    _template_title=() \
    _windows_json \
    _windows_info_opts=()
  _activities_json=""
  _windows_json=""
  # _sdk="$(
  #   sdk-version)"
  # _msg=(
  #   "Detected SDK version '${_sdk}'."
  # )
  # _msg_info \
  #   "${_msg[*]}"
  # if (( 32 < "${_sdk}" )); then
  #   _cmd=(
  #     "/system/bin/dumpsys"
  #       "window"
  #       "windows"
  #   )
  #   # _cmd=(
  #   #   "/system/bin/dumpsys"
  #   #     "activity"
  #   #     "activities"
  #   # )
  # elif (( "${_sdk}" < 28 )); then
  #   _cmd=(
  #     "/system/bin/dumpsys"
  #       "window"
  #       "windows"
  #   )
  # else
  #   _cmd=(
  #     "/system/bin/dumpsys"
  #       "window"
  #       "windows"
  #   )
  # fi
  # _msg=(
  #   "Running '${_cmd[*]}'."
  # )
  # _msg_info \
  #   "${_msg[*]}"
  # _activities="$(
  #   su \
  #     -c \
  #     "${_cmd[*]}")"
  # _activity="$(
  #   echo \
  #     "${_activities}" |
  #     grep \
  #       "  Window #" |
  #       sort \
  #         -V)"
  # _number="${_activity#  Window \#}"
  _template_title=(
    ${_title_format}
  )
  _template+=(
    ${_output_template}
  )
  _infos_flag="false"
  for _field \
    in "${_template[@]}" \
       "${_template_title[@]}"; do
    if [[ "${_field}" == "app" || \
          "${_field}" == "description" ]]; then
      _infos_flag="true"
      _msg=(
        "Required an advanced field,"
        "getting windows and activities"
        "information."
      )
      _msg_info \
        "${_msg[*]}"
      break
    fi
  done
  if [[ "${_infos_flag}" == "true" ]]; then
    # Silent mode,
    # runs faster as it
    # suppresses warnings.
    _activities_info_opts+=(
      -q
    )
    _windows_info_opts+=(
      -q
    )
    _msg=(
      "Running 'windows-info'."
    )
    _msg_info \
      "${_msg[*]}"
    _windows_json="$(
      windows-info \
        "${_windows_info_opts[@]}")"
    _msg=(
      "Running 'activities-info'."
    )
    _msg_info \
      "${_msg[*]}"
    _activities_json="$(
      activities-info \
        "${_activities_info_opts[@]}")"
  fi
  if [[ "${_windows_json}" != "" ]]; then
    echo \
      "${_windows_json}" |
      jq \
        '.'
  fi
  # for _field in "${_template_title[@]}"; do
  #   if [[ "${_field}" == "description" ]]; then
  #     _description_extract
  #   fi
  # done
  # if [[ "${_title_format}" == "  " ]]; then
  #   package
  # fi
  # echo \
  #   "${_activity}"
}

_windows_info_get() {
  true
}

_windows_list() {
  local \
    _mode="${1}" \
    _output_template="${2}" \
    _output_format="${3}" \
    _title_format="${4}" \
    _cmd=() \
    _activities \
    _args=()
    shift \
      4
  if [[ "${_mode}" == "root" ]]; then
    _args+=(
      "${_output_template}"
      "${_output_format}"
      "${_title_format}"
    )
  fi
  "_${_mode}_get" \
    "${_args[@]}"
}

_auto_detect_mode() {
  local \
    _os \
    _msg=()
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _root_requirements
    echo \
      "root"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg=(
      "Not implemented."
      "Something with 'xdotool'"
      "needs to be written."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_output_template_auto_detect() {
  local \
    _template=()
  _template=(
    "window"
    "open"
    "title"
  )
  _set_override \
    "output" \
    "template" \
    "${_template[*]}"
}

_title_format_check() {
  if [[ " ${title_format} " == *" app "* || \
        " ${output_template} " == *" app "* ]]; then
    _label_requirements
  fi
  if [[ " ${title_format} " == *" description "* || \
        " ${output_template} " == *" description "* || \
        " ${title_format} " == *" package "* || \
        " ${output_template} " == *" package "* ]]; then
    _description_requirements
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "get" \
    "mode" \
    "$(_auto_detect_mode)"
  _set_override \
    "output" \
    "template" \
    "position open title"
  _set_override \
    "title" \
    "format" \
    "description app"
  _title_format_check
  _set_override \
    "output" \
    "format" \
    "plain"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "     Got activity at date:   ${get_date}"
  _msg_info "                 Get mode:   ${get_mode}"
  _msg_info "          Output template:   ${output_template}"
  _msg_info "             Title format:   ${title_format}"
  _msg_info "            Output format:   ${output_format}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit_code="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Returns a list of the current windows.

Usage:

  ${app_name}
    [options]

  options:

     -m <mode>

       How to retrieve the windows list.
       It can be 'root'.
       Default: ${get_mode}

     -f <template>

       Template for the windows list.
       Valid field for the template are:

         position:
           Window position in sorting
           order, by default last focus.

         open:
           It reports whether the activity
           connected to the window has
           been paused.

         title:
           It displays the window title.
           See '-t' option for details onto
           what's shown in this field.

         package:
           It displays the window's application
           package name.

         app:
           It displays the window's application
           label.

       Default: '${output_template}'

     -t <title-format>

       What the 'title' field should resolve to.
       It can be:

         description:
           It displays the window description.

         app:
           It displays the application label
           when no title has been assigned.

         package:
           It displays the application package
           name.

       Default: '${title_format}'

     -o <output-format>

       Output format of the windows list.
       Default: '${output_format}'

     -h

       This message.

     -c

       Enable color output.

     -v

       Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit_code}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:f:o:l:cvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_get_mode="${OPTARG}" ;;
    f)
      override_output_template="${OPTARG}" ;;
    l)
      override_title_format="${OPTARG}" ;;
    o)
      override_output_format="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "${get_mode}"
  "${output_template}"
  "${output_format}"
  "${title_format}"
)
_show_config
_windows_list \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
