#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" \
  1>"/dev/null" || \
source \
  "${_crash_bash}"

_description_requirements() {
  _check_cmd \
    "activities-info" \
    "android-activity-utils"
}

_label_requirements() {
  _check_cmd \
    "app-name" \
    "android-app-utils"
}

_requirements() {
  _check_cmd \
    "grep"
  _check_cmd \
    "sort" \
    "coreutils"
}

_root_requirements() {
  _check_cmd \
    "su" \
    "sudo"
}

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  get_mode=""
  output_template=""
  title_format=""
  output_format=""
  color=""
  quiet=""
}

_windows_get() {
  local \
    _dumpsys \
    _cmd=() \
    _msg=()
  _cmd=(
    "/system/bin/dumpsys"
      "window"
      "windows"
  )
  _msg=(
    "Running '${_cmd[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _dumpsys="$(
    su \
      -c \
      "${_cmd[*]}")"
  _windows="$(
    echo \
      "${_dumpsys}" |
      grep \
        "  Window #" |
        sort \
          -V)"
  _windows_amount="$(
    echo \
      "${_windows}" |
      wc \
        -l)"
  _msg=(
    "Found '${_windows_amount}'"
    "windows."
  )
  _msg_info \
    "${_msg[*]}"
}

_sub_task_parse() {
  _sub_task_filter=(
    '.[] |'
      'if has('
            '"tasks") then'
        '."tasks"'
      'else'
        '[{"object-id":""}]'
      'end |'
        '.[] |'
          'select(."object-id" == "'${_sub_task}'")'
  )
  # echo \
  #   "${_activities_json}" |
  #   jq \
  #     --raw-output \
  #     '.[] | if has("tasks") then ."tasks" else [{"object-id":""}] end | .[] | select(."object-id" == "'${_sub_task}'")'
  # echo \
  #   "${_activities_json}" |
  #   jq \
  #     --raw-output \
  #     "${_sub_task_filter[*]}"
  _sub_task_item="$(
    echo \
      "${_activities_json}" |
      jq \
        --raw-output \
        "${_sub_task_filter[*]}")"
  echo "${_sub_task_item}"
  _has_history_filter=(
    'if has('
          '"history") then'
      '."history"'
    'else'
      '"null"'
    'end'
  )
  # echo \
  #   "${_sub_task_item}" |
  #   jq \
  #     --raw-output \
  #     "${_has_history_filter[*]}"
  _has_history="$(
    echo \
      "${_sub_task_item}" |
      jq \
        --raw-output \
        "${_has_history_filter[*]}")"
  # echo "${_has_history}"
  if [[ "${_has_history}" == "null" ]]; then
    _msg=(
      "Window with task '${_task_id}'"
      "has subtasks but no activity"
      "history."
    )
    _msg_info \
      "${_msg[*]}"
  else
    echo \
      "${_has_history}"
    # _has_history="$(
    #   echo \
    #     "${_activities_json}" |
    #     jq \
    #       --raw-output \
    #       '.[]."tasks".[]."history"')"
    # if [[ "${_has_history}" != "null" ]]; then
    _filter_history=(
        # '."tasks".[]."history" |'
        '.[] |'
        'select('
          '."task-id"=="'${_sub_task#t}'")'
    )
    _history_entry="$(
      echo \
        "${_has_history}" |
        jq \
          --raw-output \
          "${_filter_history[*]}")"
    if [[ "${_description_enabled}" = "true" ]]; then
      _filter_description=(
        '.[]."taskDescription"'
      )
      _description="$(
        echo \
          "${_history_entry}" |
          jq \
            --raw-output \
            "${_filter_description[*]}")"
      _descriptions+=(
        "${_description}"
      )
    fi
    if [[ "${_package_enabled}" == "true" ]]; then
      _filter_package=(
        '.[]."packageName"'
      )
      _package="$(
        echo \
          "${_history_entry}" |
          jq \
            --raw-output \
            "${_filter_package[*]}")"
      _packages+=(
        "${_package}"
      )
    fi
    if [[ "${_process_enabled}" == "true" ]]; then
      _filter_process=(
        '.[]."processName"'
      )
      _process="$(
        echo \
          "${_history_entry}" |
          jq \
            --raw-output \
            "${_filter_process[*]}")"
      _processes+=(
        "${_process}"
      )
    fi
    # fi
  fi
  true
}

_task_parse() {
  _filter_task=(
    '.[] |'
      'select(."task-id" == "'${_task_id#t}'")'
  )
  _task_item="$(
    echo \
      "${_activities_json}" |
      jq \
        --raw-output \
        "${_filter_task[*]}")"
  echo "${_task_item}"
  _has_history_filter=(
    '."history"'
  )
  _has_history="$(
    echo \
      "${_task_item}" |
      jq \
        --raw-output \
        "${_has_history_filter[*]}")"
  if [[ "${_has_history}" == "null" || \
        "${_has_history}" == "[]" ]]; then
    _msg=(
      "Window with task '${_task_id}'"
      "has no activity"
      "history."
    )
    _msg_info \
      "${_msg[*]}"
  else
    _filter_history=(
      'select('
        '."task-id"=="'${_task_id#t}'") |'
      '."history"'
    )
    _history_entry="$(
      echo \
        "${_task_item}" |
        jq \
          --raw-output \
          "${_filter_history[*]}")"
    if [[ "${_description_enabled}" = "true" ]]; then
      _filter_description=(
        '.[]."taskDescription"'
      )
      _description="$(
        echo \
          "${_history_entry}" |
          jq \
            --raw-output \
            "${_filter_description[*]}")"
      _descriptions+=(
        "${_description}"
      )
    fi
    if [[ "${_package_enabled}" == "true" ]]; then
      _filter_package=(
        '.[]."packageName"'
      )
      _package="$(
        echo \
          "${_history_entry}" |
          jq \
            --raw-output \
            "${_filter_package[*]}")"
      _packages+=(
        "${_package}"
      )
    fi
    if [[ "${_process_enabled}" == "true" ]]; then
      _filter_process=(
        '.[]."processName"'
      )
      _process="$(
        echo \
          "${_history_entry}" |
          jq \
            --raw-output \
            "${_filter_process[*]}")"
      _processes+=(
        "${_process}"
      )
    fi
  fi
}

_root_get() {
  local \
    _output_template="${1}" \
    _output_format="${2}" \
    _title_format="${3}" \
    _activities=() \
    _activities_info_opts=() \
    _app \
    _app_enabled \
    _dead=() \
    _dead_filter=() \
    _description \
    _descriptions=() \
    _description_enabled \
    _field \
    _field_title \
    _filter_description=() \
    _filter_history_entry=() \
    _filter_package=() \
    _filter_process=() \
    _filter_subtasks=() \
    _filter_tasks=() \
    _history_entry \
    _index \
    _index_task \
    _infos_flag \
    _jq_filter=() \
    _line=() \
    _lines=() \
    _msg=() \
    _non_sub_taskeds=() \
    _open \
    _open_enabled \
    _opened=() \
    _package \
    _package_enabled \
    _packages=() \
    _process \
    _process_enabled \
    _processes=() \
    _status \
    _task_id \
    _tasks_ids=() \
    _taskeds=() \
    _token \
    _tokens_ids=() \
    _template=() \
    _template_title=() \
    _windows \
    _windows_amount \
    _windows_json \
    _windows_info_opts=()
  _activities_json=""
  _windows_json=""
  _windows_get
  _template_title=(
    ${_title_format}
  )
  _template+=(
    ${_output_template}
  )
  _infos_flag="false"
  _app_enabled="false"
  _description_enabled="false"
  _package_enabled="false"
  _process_enabled="false"
  for _field \
    in "${_template[@]}" \
       "${_template_title[@]}"; do
    if [[ "${_field}" == "app" ]]; then
      _app_enabled="true"
      _infos_flag="true"
    fi
    if [[ "${_field}" == "description" ]]; then
      _description_enabled="true"
      _infos_flag="true"
    fi
    if [[ "${_field}" == "package" ]]; then
      _package_enabled="true"
      _infos_flag="true"
    fi
    if [[ "${_field}" == "process" ]]; then
      _process_enabled="true"
      _infos_flag="true"
    fi
    if [[ "${_field}" == "open" ]]; then
      _open_enabled="true"
      _infos_flag="true"
    fi
  done
  if [[ "${_infos_flag}" == "true" ]]; then
    _msg=(
      "Required an advanced field,"
      "getting windows and activities"
      "information."
    )
    _msg_info \
      "${_msg[*]}"
    # Silent mode,
    # runs faster as it
    # suppresses warnings.
    _activities_info_opts+=(
      -q
    )
    _windows_info_opts+=(
      -q
    )
    _msg=(
      "Running 'windows-info'."
    )
    _msg_info \
      "${_msg[*]}"
    _windows_json="$(
      windows-info \
        "${_windows_info_opts[@]}")"
    _msg=(
      "Running 'activities-info'."
    )
    _msg_info \
      "${_msg[*]}"
    _activities_json="$(
      activities-info \
        "${_activities_info_opts[@]}")"
  fi
  if [[ "${_windows_json}" == "" ]]; then
    _msg=(
      "No activities running"
      "or error running"
      "'windows-info'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  else
    _activities+=( $(
      echo \
        "${_windows_json}" |
        jq \
          --raw-output \
          '.[]."activity"')
    )
    _tasks_ids+=( $(
      echo \
        "${_windows_json}" |
        jq \
          --raw-output \
          '.[]."mToken"."activity-record-unknown-id"' |
        sed \
          "s/^t//g")
    )
    _tokens_ids+=( $(
      echo \
        "${_windows_json}" |
        jq \
          --raw-output \
          '.[]."mToken"."id"')
    )
    _dead_filter=(
      '.[] |'
        'if has('
              '"mAppDied") then'
          '."mAppDied"'
        'else'
          '"novalue"'
        'end'
    )
    _dead+=( $(
      echo \
        "${_windows_json}" |
        jq \
          --raw-output \
          "${_dead_filter[*]}")
    )
    for _status in "${_dead[@]}"; do
      if [[ "${_status}" == "novalue" ]]; then
        _open="true"
      elif [[ "${_status}" == "true" ]]; then
        _open="false"
      elif [[ "${_status}" == "false" ]]; then
        _open="true"
      fi
      _opened+=(
        "${_open}"
      )
    done
    echo "Opened:"
    printf \
      '%s\n' \
      "${_opened[@]}"
    _index=0
    for _token in "${_tokens_ids[@]}"; do
      _task_id="${_tasks_ids[${_index}]}"
      if [[ "${_task_id}" != "null" || \
            "${_task_id}" == "t"* ]]; then
        _filter_subtasks=(
          '.[] |'
            'if has('
                  '"tasks") then'
              '."tasks"'
            'else'
              '[ { "object-id":'
                     'null } ]'
            'end |'
              '.[]."object-id"'
        )
        _subtaskeds=( $(
          echo \
            "${_activities_json}" |
            jq \
              --raw-output \
              "${_filter_subtasks[*]}")
        )
        _msg=(
          "Checking tasks."
        )
        _msg_info \
          "${_msg[*]}"
        _filter_tasks=(
          '.[] |'
            'if has('
                  '"history") then'
              '"true"'
            'else'
              '"false"'
            'end'
        )
        _tasks_with_history=( $(
          echo \
            "${_activities_json}" |
            jq \
              --raw-output \
              "${_filter_tasks[*]}")
        )
        _filter_non_sub_tasks=(
          '.[] |'
            'if has('
                  '"tasks") then'
              '"false"'
            'else'
              '"true"'
            'end'
        )
        _non_sub_taskeds=( $(
          echo \
            "${_activities_json}" |
            jq \
              --raw-output \
              "${_filter_non_sub_tasks[*]}")
        )
        _msg=(
          "Non subtaskeds: '${_non_sub_taskeds[*]}'."
        )
        _msg_info \
          "${_msg[*]}"
        _index_task=0
        for _task in "${_taskeds[@]}"; do
          _non_sub_task="${_non_sub_taskeds[${_index_task}]}"
          if [[ "${_non_sub_task}" == "true" && \
                "${_task}" == "true" ]]; then
            _task_parse
          fi 
          _index_task=$((
            _index_task + 1))
        done
        _msg=(
          "Checking sub-tasks."
        )
        _msg_info \
          "${_msg[*]}"
        for _sub_task in "${_subtaskeds[@]}"; do
          if [[ "${_sub_task}" != "null" ]]; then
            _sub_task_parse
          fi
        done
      else
        _msg=(
          "Unknown value '${_task_id}'"
          "for task id."
        )
        _msg_info \
          "${_msg[*]}"
        if [[ "${_description_enabled}" == "" ]]; then
          _msg=(
            "Adding empty description."
          )
          _msg_info \
            "${_msg[*]}"
          _description=""
          _descriptions+=(
            "${_description}"
          )
        fi
        if [[ "${_package_enabled}" == "" ]]; then
          _package=""
          _processes+=(
            "${_package}"
          )
        fi
        if [[ "${_process_enabled}" == "" ]]; then
          _process=""
          _processes+=(
            "${_process}"
          )
        fi
      fi
      _index=$((
        _index + 1))
    done
  fi
  echo \
    "descriptions '${#_descriptions[@]}'."
  echo \
    "opened '${#_opened[@]}'."
  for _index \
    in $(seq \
           0 \
           $(( _windows_amount - 1)) ); do
    _msg=(
      "Processing window '${_index}'."
    )
    _msg_info \
      "${_msg[*]}"
    _line=()
    for _field in "${_template[@]}"; do
      if [[ "${_field}" == "position" ]]; then
        _line+=(
          "${_index}"
        )
      elif [[ "${_field}" == "title" ]]; then
        for _field_title in "${_template_title[@]}"; do
          if [[ "${_field_title}" == "description" ]]; then
            _line+=(
              "${_descriptions[${_index}]}"
            )
          elif [[ "${_field_title}" == "process" ]]; then
            _line+=(
              "${_processes[${_index}]}"
            )
          elif [[ "${_field_title}" == "package" ]]; then
            _line+=(
              "${_packages[${_index}]}"
            )
          fi
        done
      elif [[ "${_field}" == "open" ]]; then
        _line+=(
          "${_opened[${_index}]}"
        )
      else
        _msg=(
          "Unknown field '${_field}'."
        )
        _msg_error \
          "${_msg[*]}" \
          1
      fi
    done
    _lines+=(
      "${_line[*]}"
    )
  done
  printf \
    '%s\n' \
    "${_lines[@]}"
}

_windows_info_get() {
  true
}

_windows_list() {
  local \
    _mode="${1}" \
    _output_template="${2}" \
    _output_format="${3}" \
    _title_format="${4}" \
    _cmd=() \
    _activities \
    _args=()
    shift \
      4
  if [[ "${_mode}" == "root" ]]; then
    _args+=(
      "${_output_template}"
      "${_output_format}"
      "${_title_format}"
    )
  fi
  "_${_mode}_get" \
    "${_args[@]}"
}

_auto_detect_mode() {
  local \
    _os \
    _msg=()
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _root_requirements
    echo \
      "root"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg=(
      "Not implemented."
      "Something with 'xdotool'"
      "needs to be written."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_output_template_auto_detect() {
  local \
    _template=()
  _template=(
    "window"
    "open"
    "title"
  )
  _set_override \
    "output" \
    "template" \
    "${_template[*]}"
}

_title_format_check() {
  if [[ " ${title_format} " == *" app "* || \
        " ${output_template} " == *" app "* ]]; then
    _label_requirements
  fi
  if [[ " ${title_format} " == *" description "* || \
        " ${output_template} " == *" description "* || \
        " ${title_format} " == *" package "* || \
        " ${output_template} " == *" package "* ]]; then
    _description_requirements
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "get" \
    "mode" \
    "$(_auto_detect_mode)"
  _set_override \
    "output" \
    "template" \
    "position open title"
  _set_override \
    "title" \
    "format" \
    "description app"
  _title_format_check
  _set_override \
    "output" \
    "format" \
    "plain"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "     Got activity at date:   ${get_date}"
  _msg_info "                 Get mode:   ${get_mode}"
  _msg_info "          Output template:   ${output_template}"
  _msg_info "             Title format:   ${title_format}"
  _msg_info "            Output format:   ${output_format}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit_code="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Returns a list of the current windows.

Usage:

  ${app_name}
    [options]

  options:

     -m <mode>

       How to retrieve the windows list.
       It can be 'root'.
       Default: ${get_mode}

     -f <template>

       Template for the windows list.
       Valid field for the template are:

         position:
           Window position in sorting
           order, by default last focus.

         open:
           It reports whether the activity
           connected to the window has
           been paused.

         title:
           It displays the window title.
           See '-t' option for details onto
           what's shown in this field.

       Default: '${output_template}'

     -t <title-format>

       What the 'title' field should resolve to.
       It can be:

         description:
           It displays the window description.

         app:
           It displays the window application label
           when no description has been assigned.

         package:
           It displays the window application package
           name.

         process:
           It displays the window application process
           name.

         activity:
           It displays the activity name
           name.

       Default: '${title_format}'

     -o <output-format>

       Output format of the windows list.
       Default: '${output_format}'

     -h

       This message.

     -c

       Enable color output.

     -v

       Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit_code}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:f:o:l:cvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_get_mode="${OPTARG}" ;;
    f)
      override_output_template="${OPTARG}" ;;
    l)
      override_title_format="${OPTARG}" ;;
    o)
      override_output_format="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "${get_mode}"
  "${output_template}"
  "${output_format}"
  "${title_format}"
)
_show_config
_windows_list \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
